"""Automated tests for Resident persistence (T03).

These tests verify that :class:`~csms.repositories.resident_repository.ResidentRepository`
correctly stores and retrieves :class:`~csms.models.resident.Resident` objects
using a real SQLite database.  Every test receives a freshly initialised
temporary database file through the ``db_path`` fixture so that tests are
fully isolated from each other and from the development database.

Test inventory
--------------
1. test_persist_a_resident                – Resident can be saved without error.
2. test_resident_receives_an_identifier   – Saved Resident gets a non-None id.
3. test_retrieve_resident_by_identifier   – Saved Resident is returned by its id.
4. test_resident_information_is_preserved – All fields survive the round-trip.
5. test_active_status_is_preserved        – Default "Active" status survives.
6. test_missing_resident_returns_none     – Unknown id safely returns None.
7. test_persistence_across_instances      – Two repo instances share the same DB.
8. test_contact_number_stored_as_text     – Leading zero is not dropped (student-designed).
"""

import os
import tempfile

import pytest

from csms.models.resident import Resident
from csms.repositories.resident_repository import ResidentRepository


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture()
def db_path(tmp_path: object) -> str:
    """Return a path to a fresh, empty SQLite database file for one test.

    ``tmp_path`` is a built-in pytest fixture that provides a temporary
    directory unique to each test invocation.  Using it here ensures every
    test starts with a clean database and tests cannot interfere with each
    other.
    """
    return str(tmp_path / "test_csms.db")  # type: ignore[operator]


@pytest.fixture()
def repo(db_path: str) -> ResidentRepository:
    """Return a ResidentRepository backed by the test database."""
    return ResidentRepository(db_path)


def make_resident(**overrides: object) -> Resident:
    """Build an unsaved Resident with valid defaults.

    ``id`` is intentionally left at its default of ``None`` to represent a
    Resident that has not yet been persisted.
    """
    values: dict[str, object] = {
        "first_name": "Juan",
        "last_name": "Dela Cruz",
        "address": "Barangay Santo Tomas",
        "contact_number": "09171234567",
        "email": "juan@example.com",
        "status": "Active",
    }
    values.update(overrides)
    return Resident(**values)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# TEST 1 – Persist a Resident
# ---------------------------------------------------------------------------

def test_persist_a_resident(repo: ResidentRepository) -> None:
    """A valid Resident can be saved through the repository without error."""
    resident = make_resident()

    # save() must complete without raising an exception.
    saved = repo.save(resident)

    assert saved is resident  # same object is returned


# ---------------------------------------------------------------------------
# TEST 2 – Resident Receives an Identifier
# ---------------------------------------------------------------------------

def test_resident_receives_an_identifier(repo: ResidentRepository) -> None:
    """After saving, the Resident has a non-None identifier assigned by the DB.

    The identifier must not be manually hard-coded: it is generated by
    SQLite's AUTOINCREMENT mechanism so the caller never supplies it.
    """
    resident = make_resident()
    assert resident.id is None  # no id before saving

    repo.save(resident)

    assert resident.id is not None
    assert isinstance(resident.id, int)


# ---------------------------------------------------------------------------
# TEST 3 – Retrieve Resident by Identifier
# ---------------------------------------------------------------------------

def test_retrieve_resident_by_identifier(repo: ResidentRepository) -> None:
    """A Resident saved and then retrieved by its id is the correct record."""
    resident = make_resident()
    repo.save(resident)
    assigned_id = resident.id

    retrieved = repo.find_by_id(assigned_id)  # type: ignore[arg-type]

    assert retrieved is not None
    assert retrieved.id == assigned_id


# ---------------------------------------------------------------------------
# TEST 4 – Resident Information Is Preserved
# ---------------------------------------------------------------------------

def test_resident_information_is_preserved(repo: ResidentRepository) -> None:
    """All Resident fields survive the save-and-retrieve round-trip intact."""
    resident = make_resident(
        first_name="Maria",
        last_name="Santos",
        address="123 Rizal Street",
        contact_number="09981234567",
        email="maria.santos@example.com",
        status="Active",
    )
    repo.save(resident)

    retrieved = repo.find_by_id(resident.id)  # type: ignore[arg-type]

    assert retrieved is not None
    assert retrieved.first_name == "Maria"
    assert retrieved.last_name == "Santos"
    assert retrieved.address == "123 Rizal Street"
    assert retrieved.contact_number == "09981234567"
    assert retrieved.email == "maria.santos@example.com"
    assert retrieved.status == "Active"


# ---------------------------------------------------------------------------
# TEST 5 – Active Status Is Preserved
# ---------------------------------------------------------------------------

def test_active_status_is_preserved(repo: ResidentRepository) -> None:
    """A Resident with the default Active status remains Active after retrieval.

    This verifies that the T01 default-status behaviour still works end-to-end
    through the persistence layer.
    """
    # Create a Resident without specifying status – relies on T01 default.
    resident = Resident(
        first_name="Pedro",
        last_name="Reyes",
        address="Barangay San Jose",
        contact_number="09081234567",
        email="pedro.reyes@example.com",
    )
    assert resident.status == "Active"  # T01 default still works

    repo.save(resident)
    retrieved = repo.find_by_id(resident.id)  # type: ignore[arg-type]

    assert retrieved is not None
    assert retrieved.status == "Active"


# ---------------------------------------------------------------------------
# TEST 6 – Missing Resident Is Handled Safely
# ---------------------------------------------------------------------------

def test_missing_resident_returns_none(repo: ResidentRepository) -> None:
    """Querying a non-existent id returns None without crashing."""
    result = repo.find_by_id(99999)

    assert result is None


# ---------------------------------------------------------------------------
# TEST 7 – Persistence Works Across Repository Instances
# ---------------------------------------------------------------------------

def test_persistence_across_repository_instances(db_path: str) -> None:
    """Data saved through one repository instance is visible to a second one.

    This test demonstrates that the persistence layer uses real on-disk
    storage, not just an in-memory Python structure.  If the repository were
    backed by a plain list or dict, the second instance would see an empty
    store and find_by_id would return None.
    """
    # First repository instance – used to save the Resident.
    repo_one = ResidentRepository(db_path)
    resident = make_resident(first_name="Ana", last_name="Reyes")
    repo_one.save(resident)
    saved_id = resident.id

    # Second repository instance – created independently, same database file.
    repo_two = ResidentRepository(db_path)
    retrieved = repo_two.find_by_id(saved_id)  # type: ignore[arg-type]

    assert retrieved is not None
    assert retrieved.id == saved_id
    assert retrieved.first_name == "Ana"
    assert retrieved.last_name == "Reyes"


# ---------------------------------------------------------------------------
# TEST 8 – Student-Designed: Contact Number Is Stored as Text
# ---------------------------------------------------------------------------
#
# What this test verifies:
#   The contact_number field is stored in SQLite as TEXT, so the leading zero
#   in a Philippine mobile number (e.g. "09171234567") is never silently
#   dropped.  If the column were declared as INTEGER, SQLite would store the
#   value 9171234567 and the leading zero would be lost on retrieval.
#
# Why this scenario was selected:
#   The T03 requirements explicitly call out that "09171234567 must NOT become
#   9171234567".  A dedicated test for this makes the contract visible and
#   catches any future schema change that accidentally declares the column
#   as a numeric type.
#
# What failure it is designed to detect:
#   If the database schema is changed so that contact_number is stored as
#   INTEGER or NUMERIC, the retrieved value would be the integer 9171234567
#   (a string without the leading zero).  This test would then fail at the
#   exact assertion that compares the retrieved string to "09171234567".

def test_contact_number_leading_zero_is_preserved(repo: ResidentRepository) -> None:
    """The leading zero of a Philippine mobile number survives the DB round-trip."""
    resident = make_resident(contact_number="09171234567")
    repo.save(resident)

    retrieved = repo.find_by_id(resident.id)  # type: ignore[arg-type]

    assert retrieved is not None
    assert retrieved.contact_number == "09171234567"
    # Explicitly confirm it is a string, not a number missing its leading zero.
    assert isinstance(retrieved.contact_number, str)
    assert retrieved.contact_number.startswith("0")
