"""SQLite database integration for the CSMS application (T03 + T09).

This module is responsible for one thing: providing a live SQLite connection
and ensuring the required schema exists.  All other modules obtain their
connection through :func:`get_connection` so the database path is always
read from the Flask application configuration.

The ``residents`` table stores Resident records (T03).  The ``contact_number``
column is declared as TEXT so that leading zeroes (e.g. ``09171234567``) are
preserved exactly as entered.

The ``service_requests`` table stores Service Request records (T09).  The
``date_requested`` column is stored as TEXT in ``YYYY-MM-DD`` ISO-8601 format,
which is SQLite's recommended approach for date values and allows correct
lexicographic ordering.  The ``resident_id`` column references the Resident
who owns the request; Resident personal information is not duplicated here.

SQLite auto-assigns row identifiers through the
``id INTEGER PRIMARY KEY AUTOINCREMENT`` column for both tables, which
satisfies the requirement that identifiers are generated by the persistence
layer, not hard-coded by callers.
"""

import sqlite3


def init_db(database_path: str) -> None:
    """Create the database schema if it does not already exist.

    This function is idempotent: calling it on an existing database leaves
    the data untouched because the ``CREATE TABLE IF NOT EXISTS`` form is used.

    Args:
        database_path: Filesystem path to the SQLite database file, or the
            special string ``":memory:"`` for an in-process database.
    """
    connection = sqlite3.connect(database_path)
    try:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS residents (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                first_name      TEXT    NOT NULL,
                last_name       TEXT    NOT NULL,
                address         TEXT    NOT NULL,
                contact_number  TEXT    NOT NULL,
                email           TEXT    NOT NULL,
                status          TEXT    NOT NULL DEFAULT 'Active'
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS service_requests (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                resident_id     INTEGER NOT NULL,
                service_type    TEXT    NOT NULL,
                description     TEXT    NOT NULL,
                date_requested  TEXT    NOT NULL,
                status          TEXT    NOT NULL DEFAULT 'Pending'
            )
            """
        )
        connection.commit()
    finally:
        connection.close()


def get_connection(database_path: str) -> sqlite3.Connection:
    """Open and return a new SQLite connection for the given path.

    The connection is configured with ``row_factory = sqlite3.Row`` so that
    result rows behave like dictionaries (accessible by column name) in
    addition to supporting positional access.

    The caller is responsible for closing the connection when finished.

    Args:
        database_path: Filesystem path to the SQLite database file, or
            ``":memory:"`` for a transient in-process database.

    Returns:
        An open :class:`sqlite3.Connection`.
    """
    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    return connection
